### ISSUE TITLE
What is this project?

### ISSUE THREAD

**Issue by CWSpear** [cloud9ide/emmet-core#1]
What exactly is this project? There's no information in the README. All I've been able to find is a couple Ace Editor references to the `emmet.js` file in this repo.

Is this related to [emmetio/emmet](https://github.com/emmetio/emmet)? Is this some sort of non-fork from there? Does another (more active) version of this code exist? Or is this the only option for integrating emmet into the Ace Editor?

Specifically, a demo from the official Ace site references the code here: http://ace.c9.io/demo/emmet.html, and I found a few other posts referencing that code which all leads to this mysterious project here.

**Comment by nightwing** [comment]
See updated readme,

**Comment by CWSpear** [comment]
Thanks!
