### ISSUE TITLE
How could I use other emmet versions?

### ISSUE THREAD

**Issue by mortalis13** [cloud9ide/emmet-core#2]
Hi. Could you help me understand how to use another version?
I downloaded `emmet-app.js` and `snippets.json` files from the `emmet-sublime` repository. But how can I change the .js script so it works with the editor?

As I understand there should be a global `emmet` variable for the `ext-emmet.js` script. But how to define it properly and what other things should I do to make it work?

Thanks.

**Comment by nightwing** [comment]
The version on emmet-sublime probably won't work since it is newer than this and ace/ext/emmet needs to be updated to work with it.

**Comment by nightwing** [comment]
It should work with the newer version now. was fixed by https://github.com/ajaxorg/ace/commit/04601f746acbed0a9b4b821806d951eea0f42210, just having global emmet defined should be enough.
